data = {
    'title': [
        # Positive / Uplifting
        "Local Community Comes Together for Annual Festival",
        "New Community Center Opens in Neighborhood",
        "Students Raise Funds for Charity Event",
        "City Park Gets a Revamp for Families",
        "Local Bakery Wins National Award",
        "School Launches Mentorship Program for Youth",
        "New Playground Built for Children in Low-Income Area",
        "Local Theater Receives Grant for New Productions",
        "Community Garden Thrives in City Neighborhood",
        "Nonprofit Organization Provides Meals to the Needy",
        "Local Heroes Rescue Family from Burning Building",
        "New Tech Startup Promises to Revolutionize Education",
        "City's Youth Leadership Program Gains National Recognition",
        "Local Artist’s Work Featured in International Exhibit",
        "Volunteer Group Cleans Up Local Beach",
        "Local High School Wins State Championship",
        "Charity Run Raises Record Amount for Local Hospital",
        "Community Comes Together to Support Local Farmers",
        "Innovative New App Helps Seniors Stay Connected",
        "Neighborhood Watch Program Leads to Safer Streets",
        
        # Terrorism / Protest / Political Unrest / Riot
        "Protests Erupt Over New Policy Changes",
        "Terrorist Attack in Major City Shocks Residents",
        "Political Unrest Escalates in Major City",
        "Violent Clashes Between Protesters and Police",
        "Demonstrators Rally Against Government Actions",
        "Tensions Rise as Protesters Demand Justice",
        "National Guard Deployed Amid Civil Unrest",
        "Protesters Take to the Streets for Climate Action",
        "Security Forces Respond to Violent Demonstrations",
        "Activists Call for Change Amid Ongoing Protests",
        "Police Clash with Protesters During Anti-Government Rally",
        "Students Stage Sit-In at University to Demand Policy Changes",
        "Civil Rights Leaders Organize March for Equality",
        "Nationwide Protests Spark Debate on Policy Reform",
        "Rioters Cause Damage During Protest Over Police Brutality",
        "Public Outcry Grows Over Recent Government Decisions",
        "Demonstrators Occupy City Hall Demanding Action",
        "Protest Against Inequality Draws Thousands",
        "Activists Arrested During Protest for Environmental Justice",
        "Protests Erupt Following Controversial Court Ruling",

        # Natural Disasters
        "Major Earthquake Strikes the City",
        "Hurricane Causes Widespread Destruction",
        "Flooding Leads to Evacuations in Coastal Town",
        "Tornado Touches Down, Damaging Homes and Businesses",
        "Severe Drought Affects Local Farmers",
        "Wildfires Ravage Forest Areas, Homes Evacuated",
        "Residents Prepare for Incoming Hurricane",
        "Landslide Buries Homes, Emergency Crews Respond",
        "Snowstorm Hits City, Causing Major Disruptions",
        "Cyclone Approaches, Authorities Issue Warnings",
        "Flash Flooding Traps Residents in Their Homes",
        "Severe Storms Cause Power Outages Across the Region",
        "Authorities Issue Tornado Warnings in Several Counties",
        "Earthquake Aftershocks Continue to Rattle Residents",
        "Heatwave Breaks Records in Several States",
        "Floodwaters Rise, Threatening Downtown Area",
        "Community Bands Together for Disaster Relief Efforts",
        "Residents Rebuild After Devastating Fire",
        "Hurricane Relief Fund Raises Millions for Victims",
        "Severe Weather Causes Travel Disruptions Nationwide",

        # Others
        "Scientists Discover New Species in Amazon Rainforest",
        "New Technology Unveiled at Annual Conference",
        "Study Reveals Benefits of Meditation for Mental Health",
        "Local Artist Showcases Work in National Gallery",
        "New Research Breakthrough in Renewable Energy",
        "Company Launches Innovative App for Smart Homes",
        "International Space Station Welcomes New Crew",
        "Documentary Explores Climate Change Impact",
        "Bookstore Hosts Author Event for Local Writers",
        "Museum Opens Exhibition on Ancient Civilizations",
        "New Study Shows Link Between Diet and Mental Health",
        "Tech Giants Collaborate on Artificial Intelligence Ethics",
        "Local College Introduces Innovative New Curriculum",
        "Art Installation Sparks Conversation About Climate Change",
        "Study Finds Correlation Between Sleep and Productivity",
        "Groundbreaking Research in Cancer Treatment Announced",
        "City's Public Library Launches Digital Literacy Program",
        "Local Farm Hosts Educational Workshops for Kids",
        "New Film Highlights Stories of Unsung Heroes",
        "Community Radio Station Promotes Local Artists"
    ],
    'category': [
        # Positive / Uplifting
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        'Positive / Uplifting',
        
        # Terrorism / Protest / Political Unrest / Riot
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
        'Terrorism / Protest / Political Unrest / Riot',
            # Natural Disasters
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',
        'Natural Disasters',

        # Others
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
        'Others',
    ]
}

